name: nlu
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.8.3
  - aiosignal=1.3.1
  - anyio=3.6.2
  - appdirs=1.4.4
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - astroid=2.14.2
  - asttokens=2.2.1
  - async-timeout=4.0.2
  - attrs=22.2.0
  - babel=2.11.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=6.0.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - catalogue=2.0.8
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - colorama=0.4.6
  - comm=0.1.2
  - commonmark=0.9.1
  - confection=0.0.4
  - contourpy=1.0.7
  - cryptography=39.0.0
  - cycler=0.11.0
  - cymem=2.0.7
  - cython-blis=0.7.9
  - dataclasses=0.8
  - debugpy=1.6.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.6
  - docker-pycreds=0.4.0
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=1.2.0
  - flit-core=3.8.0
  - fonttools=4.38.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - future=0.18.3
  - gitdb=4.0.10
  - gitpython=3.1.30
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_resources=5.10.2
  - ipykernel=6.20.2
  - ipython=8.8.0
  - ipython_genutils=0.2.0
  - isort=5.9.3
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.17.3
  - jupyter_client=7.4.9
  - jupyter_core=5.1.4
  - jupyter_events=0.6.3
  - jupyter_server=2.1.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.19.0
  - kiwisolver=1.4.4
  - langcodes=3.3.0
  - lazy-object-proxy=1.6.0
  - lcms2=2.14
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libtiff=4.5.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - markupsafe=2.1.2
  - matplotlib-base=3.6.3
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mistune=2.0.4
  - multidict=6.0.4
  - munkres=1.1.4
  - murmurhash=1.0.9
  - nbclassic=0.4.8
  - nbclient=0.7.2
  - nbconvert=7.2.8
  - nbconvert-core=7.2.8
  - nbconvert-pandoc=7.2.8
  - nbformat=5.7.3
  - nbstripout=0.6.1
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - numpy=1.24.1
  - openai=0.27.4
  - openjpeg=2.5.0
  - openpyxl=3.1.0
  - openssl=3.1.0
  - packaging=23.0
  - pandas=1.5.3
  - pandas-stubs=1.5.2.230105
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathtools=0.1.2
  - pathy=0.10.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.6.2
  - plotly=5.13.0
  - pooch=1.6.0
  - preshed=3.0.8
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pydantic=1.10.5
  - pygments=2.14.0
  - pylint=2.16.2
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.11.0
  - python-dateutil=2.8.2
  - python-dotenv=1.0.0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.4
  - python_abi=3.11
  - pytz=2022.7.1
  - pyyaml=6.0
  - pyzmq=25.0.0
  - readline=8.1.2
  - requests=2.28.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=12.6.0
  - scikit-learn=1.2.1
  - scipy=1.10.0
  - send2trash=1.8.0
  - sentry-sdk=1.14.0
  - setproctitle=1.3.2
  - shellingham=1.5.1
  - six=1.16.0
  - smart_open=5.2.1
  - smmap=3.0.5
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - spacy=3.5.0
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.4
  - srsly=2.4.5
  - stack_data=0.6.2
  - tenacity=8.1.0
  - terminado=0.17.1
  - thinc=8.1.7
  - threadpoolctl=3.1.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tomlkit=0.11.1
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.8.1
  - typer=0.7.0
  - types-pytz=2022.7.1.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.14
  - wandb=0.13.9
  - wasabi=1.1.1
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.4.2
  - wheel=0.38.4
  - wrapt=1.14.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.8.2
  - zeromq=4.3.4
  - zipp=3.11.0
  - zstd=1.5.2
  - pip:
      - en-core-web-sm==3.5.0
      - lxml==4.9.2
      - pip==23.0.1
      - protobuf==3.19.5
      - python-docx==0.8.11
      - setuptools==67.6.1
